services:
  yeti-mcp:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - YETI_ENDPOINT=${YETI_ENDPOINT}
      - YETI_API_KEY=${YETI_API_KEY}
    volumes:
      - ../:/app
    networks:
      - default
      - dev_default
      - timesketch_default

networks:
  default:
    driver: bridge
  dev_default:
    external: true
  timesketch_default:
    external: true
