version: '3.8'
services:
  yeti-mcp:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - YETI_ENDPOINT=${YETI_ENDPOINT}
      - YETI_API_KEY=${YETI_API_KEY}
    volumes:
      - ../:/app
    networks:
      - dev_default
      - timesketch_default

networks:
  dev_default:
    external: true
  timesketch_default:
    external: true
